import re
import os
import pytest
from returns.result import Success

from test_support import with_remarks, snapshot, snapshot_test_pdf
from parsita import ParserContext, lit, reg, rep, Parser, ParseError, opt, until, any1, Failure

r"""
 _____  _____  ______ 
|  __ \|  __ \|  ____|
| |__) | |  | | |__   
|  ___/| |  | |  __|  
| |    | |__| | |     
|_|    |_____/|_|     
"""


@with_remarks("tests/in/pdf_with_multiple_added_pages")
def test_pdf_with_inserted_pages(snapshot):
    snapshot_test_pdf("pdf_longer _remarks.pdf", snapshot)


@with_remarks("tests/in/highlighter-test")
def test_pdf_with_glyphrange_highlights(snapshot):
    snapshot_test_pdf("docsfordevelopers _remarks.pdf", snapshot)


@with_remarks("demo/on-computable-numbers/xochitl")
def test_can_process_demo_with_default_args():
    assert os.path.isfile(
        "tests/out/1936 On Computable Numbers, with an Application to the Entscheidungsproblem - A. M. Turing _remarks.pdf")


@with_remarks("tests/in/v2_notebook_complex")
def test_can_handle_drawing_with_many_scribbles():
    assert os.path.isfile("tests/out/Gosper _remarks.pdf")


@with_remarks("tests/in/v2_book_with_ann")
def test_can_handle_book():
    assert os.path.isfile("tests/out/Gosper _remarks.pdf")


r"""
 __  __            _       _                     
|  \/  |          | |     | |                    
| \  / | __ _ _ __| | ____| | _____      ___ __  
| |\/| |/ _` | '__| |/ / _` |/ _ \ \ /\ / / '_ \ 
| |  | | (_| | |  |   < (_| | (_) \ V  V /| | | |
|_|  |_|\__,_|_|  |_|\_\__,_|\___/ \_/\_/ |_| |_|

Lessons about parsita.

1. When invoking a parser, you _must_ consume all the tokens until the EOD or you will get a failure
   You can do this with `{...} << whatever`
"""


def assert_parser_succeeds(parser: Parser, input_string: str, expected_output=""):
    result = parser.parse(input_string)
    match result:
        case Success(value):
            output = value
            if expected_output:
                assert expected_output == output
        case Failure(error):
            raise error
    assert type(result) is Success, result.failure()


any_char = reg(r'.') | lit("\n")
whatever = rep(any_char)
newline = lit('\n')

to_newline = reg(r'[^\n]+')

obsidian_tag = reg(r"#([a-z/])+")
yaml_property = lambda k, v: k >> lit(":\n") >> v
frontmatter = opt(
    lit('---') << newline >>
    yaml_property(lit("tags"), lit("- ") >> lit("'") >> obsidian_tag >> lit("'")) >> rep(newline) >>
    lit("---") >> rep(newline)
)
autogeneration_warning = lit("""> [!WARNING] **Do not modify** this file
> This file is automatically generated by Scrybble and will be overwritten whenever this file in synchronized.
> Treat it as a reference.""")
h = lambda n, c: lit(n + " ") >> c

@with_remarks("tests/in/highlighter-test")
@pytest.mark.markdown
def test_generated_markdown_has_autogeneration_warning():
    has_warning = (until(autogeneration_warning) << autogeneration_warning >> whatever)
    with open("tests/out/docsfordevelopers _obsidian.md") as f:
        assert_parser_succeeds(has_warning, f.read())


@with_remarks("tests/in/v3_markdown_tags")
@with_remarks("tests/in/highlighter-test")
@pytest.mark.markdown
def test_generated_markdown_heading_is_positioned_correctly():
    rmdoc_title = h("#", to_newline)

    with open("tests/out/docsfordevelopers _obsidian.md") as f:
        content = f.read()
        assert_parser_succeeds(frontmatter >> rmdoc_title << whatever, content, "docsfordevelopers")
    with open("tests/out/tags test _obsidian.md") as f:
        content = f.read()
        assert_parser_succeeds(frontmatter >> rmdoc_title << whatever, content, "tags test")


@with_remarks("tests/in/v3_markdown_tags")
@pytest.mark.markdown
def test_yaml_frontmatter_is_valid():
    with open('tests/out/tags test _obsidian.md') as f:
        content = f.read()
        assert_parser_succeeds(frontmatter << whatever, content)

# @with_remarks("tests/in/v3_typed_text")
# def test_something():
#     raise Exception("hi")
